### ISSUE TITLE
Update GO db as latest version GO

### ISSUE THREAD

**Issue by DiracZhu1998** [Bioconductor/GO.db#2]
Dear Sir or Madam, 
Thank you for giving us GO.db, such a good package.
I am wondering how can I update GOSOURCEDATE: 2020-05-02 to latest?

GODb object:
| GOSOURCENAME: Gene Ontology
| GOSOURCEURL: http://current.geneontology.org/ontology/go-basic.obo
| GOSOURCEDATE: 2020-05-02
| Db type: GODb
| package: AnnotationDbi
| DBSCHEMA: GO_DB
| GOEGSOURCEDATE: 2019-Jul10
| GOEGSOURCENAME: Entrez Gene
| GOEGSOURCEURL: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA
| DBSCHEMAVERSION: 2.1

Thank you for your help!
Yuanzhen

**Comment by hpages** [comment]
by upgrading to the latest version of Bioconductor: BioC 3.14 (requires R 4.1.2)

H.
