### ISSUE TITLE
GOCCCHILDREN and GOCCOFFSPRING yields incorrect result

### ISSUE THREAD

**Issue by janjoy** [Bioconductor/GO.db#3]
Hello,
I am trying to use the GOCCCHILDREN to get direct child terms and GOCCOFFSPRING to get all child, and grandchild terms. However, the results obtained are far less than what is observed on (http://geneontology.org/).
For example, for mitochondrion `GOCCCHILDREN[["GO:0005739"]]` gives result
` part of      part of      part of      part of      part of 
"GO:0005740" "GO:0005759" "GO:0020023" "GO:0044290" "GO:0098798" `
Whereas under Neighborhood (http://amigo.geneontology.org/amigo/term/GO:0005739) I find so many more direct child terms. Same thing for GOCCOFFSPRING.
What would be a good way to proceed further?
Thanks!

**Comment by hpages** [comment]
Hi @janjoy, have you tried to ask your question on the [Bioconductor support site](https://support.bioconductor.org)? You will have a much better chance to get an answer there.
Best,
H.
