### ISSUE TITLE
Which species does GO.db use?

### ISSUE THREAD

**Issue by howtofindme** [Bioconductor/GO.db#4]
hi,
 Thanks for your job!

could you tell me which species does GO.db use?  Since now we have human ,rat ,mouse ,and etc......

does different species  have the all the same  GO terms ? 
can I use GO.db for human, mouse  or rat  and why?

best wishes,
Young

**Comment by howtofindme** [comment]
> hi, Thanks for your job!
> 
> could you tell me which species does GO.db use? Since now we have human ,rat ,mouse ,and etc......
> 
> does different species have the all the same GO terms ? can I use GO.db for human, mouse or rat and why?
> 
> best wishes, Young

And if I want to use go terms for rat , what should I do?

**Comment by hpages** [comment]
**GO.db** is a Bioconductor package that is just a packaging of the Gene Ontology. Sounds like you should spend some time familiarizing yourself with what the Gene Ontology is and what kind of data it provides. Maybe a good starting point is https://en.wikipedia.org/wiki/Gene_Ontology

If you still have questions about how to use the package, or how to use any other Bioconductor package, please ask on the [Bioconductor support site](https://support.bioconductor.org/). GitHub issues are preferrably for bug reports or feature requests. Thanks!
